### ISSUE TITLE
Usar no windows 64 bits

### ISSUE THREAD

**Issue by incorpore** [andpena/FinancialData#3]
Estou tendo dificuldade de utilizar no 64bits, preciso fazer alguma alteração? o tryd é 64 tbm!

**Comment by andpena** [comment]
É necessário registrar a DLL do RTD novamente.

Abra o Tryd 64 clicando com botão direito do mouse e vá na opção Abrir como
Administrador.

Após após o Tryd 64 vá para opção de registrar a DLL. Isso deve resolver
seu problema.

**Comment by andpena** [comment]
OK!?
